[package]
name = "crystal_dll"
version = "1.0.0"
edition = "2021"

[features]
#default = ["debug"]
#default = []
debug = []

[lib]
crate-type = ["cdylib"]

[dependencies]
gm_utils = { path = "./crates/gm_utils" }
base64 = "0.22.1"
chrono = "0.4.39"
crystal-server = { git = "https://github.com/Crystal-Server/rust-client.git", rev = "a157b73c8e5cfc793e1b99d8af48d4a5ec83944e", features = [
    #"__dev",
] }
futures-util = "0.3.31"
parking_lot = "0.12.3"
tokio = { features = ["rt-multi-thread", "time", "net"], version = "1.43.0" }
tracing-subscriber = "0.3.19"
