[package]
name = "crystal_dll"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
chrono = "0.4.39"
crystal-server = { git = "https://github.com/Crystal-Server/rust-client.git", rev = "d68ecdda03c49b538b9749b8e1565cc0fb9ad09f" }
futures-util = "0.3.31"
parking_lot = "0.12.3"
tokio = { features = ["rt-multi-thread", "time", "net"], version = "1.43.0" }
